### ISSUE TITLE
Add samples about working with files and databases such as .dat

### ISSUE THREAD

**Issue by Fabxx** [Fabxx/Programming_Languages#12]
Add functions for both binary and text files such as:

fread, fwrite, fprintf, fscanf, fseek(SEEK_CUR, SEEK_SET, SEEK_END), ftell, fopen, fclose, fgets, fputs, fputc, fgetc, rewind(), feof().
and why those should be used and when specificly, with a struct/array/data types.

**Comment by Sqrdelta** [comment]
add an example of how to delete a simple record from a file. Struct, string, integer ecc.
